# Generated by Django 5.2.6 on 2025-09-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0004_alter_channel_options_socialnetwork_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('content', 'Content count'), ('views', 'Views'), ('followers', 'Followers')], max_length=30)),
                ('min_value', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('channel_social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='channel.channelsocialaccount')),
            ],
            options={
                'ordering': ['-min_value'],
            },
        ),
    ]
