# Generated by Django 5.2.6 on 2025-09-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0005_alter_kpiformula_options'),
        ('channel', '0004_alter_channel_options_socialnetwork_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsocialstats',
            name='channel_social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_stats', to='channel.channelsocialaccount'),
        ),
        migrations.DeleteModel(
            name='KPIFormula',
        ),
    ]
